### ISSUE TITLE
Do we need to do all of that stuff to make links work?

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-analytics#1]
@scloo :
Looking at this code:
https://github.com/ICTatRTI/coconut-reports/blob/master/_attachments/app/views/MenuView.coffee#L8-L25

I see a lot of code (and repeated code) that simply lets links be clicked on. Is that necessary? Clicking on a link will take you to a new route, which the router will handle. The animation actions (setting items to active, etc) should all be automatically handled by material design lite. Am I missing something?

**Comment by scloo** [comment]
I know there are a lot of repeated codes right now that I was going to refactor. I just want to get something working first.
The events callback is basically to update the UI such as changing the Top title to show where the user is at. Clicking a link will hand it over to the router but I feel that the view update should be handled within the view itself. Which is the reason for the events binding.

Changing the menu items to active or inactive to show where the user is at on the menu list. I don't think that is part of the Material Design Lite. Unless there was something I missed in MDL. Ultimately it boils down to how we want the UI to look. Do we want the side drawer to remain fixed so that the user can select the menu without having to click the menu icon each time to open the menu. Or do we want to hide the menu each time a menu item is clicked. In the latter case, then we have no need for the active status.

**Comment by mikeymckay** [comment]
Ah ok. This makes sense now. I didn't realize it was for extra animation. Also my mistake was reading the target code as a need to actually update the URL. I see now.
