### ISSUE TITLE
Add user does not create user record

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#151]
Is this function just disabled until we work out the DHIS2 org hierarchy issues?

**Comment by scloo** [comment]
It works on my local machine. For some reason it does not work on Cococloud. 
@mikeymckay , could this have something to do with permission writing to the couchDB?

**Comment by scloo** [comment]
@mikeymckay What does this error message mean, when I tried to save a new user record?
CustomPouchError {status: 409, name: "conflict", message: "Document update conflict", error: true, reason: "Document update conflict."…}

**Comment by scloo** [comment]
@mikeymckay I think I know what causes the error message. I think it is due to  a conflicting _id. For some reason when I save a new user, I set _id  to 'user.username' but upon saving the _id became 'user.0772632770'. The user name became a series of digits. If you get the chance, can you take a look at the codes at formSave()  in UserView?

**Comment by scloo** [comment]
Problem fixed.
