### ISSUE TITLE
"undefined" fields in person document

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#220]
I spotted the following this morning. Why are these fields "undefined"
![image](https://cloud.githubusercontent.com/assets/329768/17437446/bfbc8674-5aeb-11e6-82c7-e63d1bbd6877.png)

![image](https://cloud.githubusercontent.com/assets/329768/17437456/d3293bda-5aeb-11e6-8d04-4c105f6ab4c8.png)

**Comment by scloo** [comment]
The reason for this is because every household member records have different fields. I have to extract all the available fields and then do a label translate. Since I have not encountered that particular household member record, I never encountered those fields. And so they remain undefined. I'll have to find out what are the names of those fields. Should not be too difficult to fix.

**Comment by scloo** [comment]
Fixed
