### ISSUE TITLE
Graph: Number of Cases does not handle multiple years gracefully

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#275]
![image](https://cloud.githubusercontent.com/assets/329768/20010988/8034e62c-a280-11e6-8a09-faf8316f3b54.png)

**Comment by scloo** [comment]
If I am not mistaken, the  original purpose of this graph is to compare current year with the last. In which case the graph should be titled 'Number of Cases for current and last year". But since the date selector allows multiple years selection, the legend 'Current' and 'Last Year' does not make good sense.
So we probably need to define the scope for this graph. Is it for comparing one year with the last, or is it meant to be comparing a range of years. If it is the latter, then the legend makes no sense.

**Comment by gmcressman** [comment]
I agree Steve. This graph could be generalized to compare the time period selected using the date-picker, with the previous time period of the same duration As the graph is now, it should simply default to the current year and should ignore the date range selected using the date picker. If that is the case, then the graph title should be changes as you suggest.

**Comment by scloo** [comment]
This graph is defaulted to comparing current year vs last year and ignoring the date range selector. The graph title has been changed to reflect this.
