### ISSUE TITLE
DHIS2: TEST DHIS Connection fails on URL

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#296]
![image](https://cloud.githubusercontent.com/assets/329768/25148674/a36ab6f8-2449-11e7-81f7-e415c90efd2a.png)

**Comment by gmcressman** [comment]
More of the same: the URL is not being validated and tested properly, and there is no graceful error handling or messaging.

![image](https://cloud.githubusercontent.com/assets/329768/25148768/0e2d68d2-244a-11e7-8247-dd313cceea08.png)

**Comment by scloo** [comment]
This first error screen is due to the fact that we are using https for cococloud.co but dhis2 does not have https but only http. Browser technology does not allow mixed protocol. To resolve it, we have to install cert for dhis2 server.

**Comment by gmcressman** [comment]
Makes sense. What are you thoughts on getting a clean DHIS2 install? What do you think might be the most efficient way to get that done?

**Comment by scloo** [comment]
This is already a clean install. It is a new droplet and and a clean install of DHIS2. The old droplet was compromised and had to be shut down.

I'm now looking into getting a SSL cert for this server.

**Comment by gmcressman** [comment]
Clean = empty database. We currently have the Sierra Leone demo database installed.

**Comment by scloo** [comment]
Dhis2 Test connection fixed. 
First error message encountered:
There are 2 issues involved. 1) Cross-Origin request  2) Mixed Content (https-http connection.)
Steps taken to resolve issue:
- install ssl cert for dhis2.zanzibar.ictedge.org
- configure Nginx for reverse proxy
- Configure Nginx for Cross-Domain-origin
- fine tune Nginx conf.

Second error message encountered:
Looks like the dhis server was not running. Hence not responding. Could be due to the docker container has stopped.

**Comment by scloo** [comment]
DHIS2 database has been cleaned. It is now a new database with no data.

**Comment by gmcressman** [comment]
Done.

**Comment by gmcressman** [comment]
Steve, can you document this setup for other people to replicate?
