### ISSUE TITLE
Incorrect app title in login dialogue

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#62]
App title in login dialogue should be the app title configured by the administrator. This same app title should be used throughout the app, including at the top of the hamburger/draw nav menu. This title and the app icon should eventually be configurable by an authorized admin. I believe we can leave the background of the login display as it is, with the Coconut logo. 

![image](https://cloud.githubusercontent.com/assets/329768/15677819/e9fb7d92-2719-11e6-9638-08b783defdd6.png)

**Comment by scloo** [comment]
The title can now be specified in the System Settings.

**Comment by gmcressman** [comment]
@scloo : If the app title or logo are changed, can the screen be refreshed easily after the user selects the UPDATE button? That would show the effects of the changes to the user automatically. Otherwise the user must know to refresh the browser. Also, how much time would it take to enable the user to upload a logo? I expect that will take a modal dialog.

**Comment by scloo** [comment]
Because of the Backbone views are modular, we need to serenader the whole screen. That means reloading the entire screen. For now I have just put a message to reload screen, in the popup message that says "Configuration has been saved."

For the user to upload files, I'll need to refer to Mike for now because it involves saving the logo image inside couchdb. And I think this should be a new ticket for this.
