### ISSUE TITLE
Errors Detected by System: Change message if there are no errors

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#77]
![image](https://cloud.githubusercontent.com/assets/329768/15713627/32b1ea0a-27e5-11e6-83c7-e4e2aa460699.png)

If there are no in last 2 days, do not display "The following system errors have occurred in the last 2 days:" 

I cannot get this report to work on the old version, so I cannot see how the date selector interacts with this report.

**Comment by scloo** [comment]
Question: Since this report is supposed to range the filter in the last 2 days (I think) , does it make sense to have the Date Selector for this System Error report?

**Comment by gmcressman** [comment]
@mikeymckay can you answer Steve's question above?

**Comment by mikeymckay** [comment]
This report queries the database for any errors for any date range. So we do need the date selector. Here is the view it is supposed to be using: http://cococloud.co/_utils/database.html?zanzibar/_design/zanzibar/_view/errorsByDate

**Comment by scloo** [comment]
@mikeymckay . The current codes check whether the startDate and endDate are specified or not, and if not use the dates for the last 2 days. However the startDate and endDate are always going to be specified due to the DateSelector defaults. So it will never default to the last 2 days. At this point the only way to get the last 2 days is to specify it in the DateSelector. Otherwise it will filter by whatever dates is specified in the DateSelector.
